INSERT INTO categories (id, name)
VALUES
	(2,'Testing'),
	(12,'HTML and Markup'),
	(22,'Time and Space'),
	(32,'Documents and Reports'),
	(42,'CSS'),
	(52,'Developer Tools'),
	(62,'Web Apps, Services and Interaction'),
	(72,'Convenience'),
	(82,'Dependency Injection Frameworks'),
	(92,'Cloud Computing');

INSERT INTO project (enabled, id, description, name, issues_url, sourcecode_url, website_url, category_id, artifact_id, group_id)
VALUES
	('Y', 2,'A pure-Java Markdown processor based on a parboiled PEG parser supporting a number of extensions','pegdown','https://github.com/sirthias/pegdown/issues','https://github.com/sirthias/pegdown','http://pegdown.org',12,NULL,NULL),
	('Y', 12,'The Apache PDFBox library is an open source Java tool for working with PDF documents. This project allows creation of new PDF documents, manipulation of existing documents and the ability to extract content from documents.','PDFBox','https://issues.apache.org/jira/browse/PDFBOX/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel','https://github.com/apache/pdfbox','https://pdfbox.apache.org/',32,NULL,NULL),
	('Y', 22,'A simple and robust layer on top of Selenium and PhantomJS. It also supports Chrome and Firefox. SauceLabs support is ongoing.','Simplelenium','https://github.com/dgageot/simplelenium/issues','https://github.com/dgageot/simplelenium','',2,NULL,NULL),
	('Y', 32,'A pure Java implementation of Cucumber that supports the most popular programming languages for the JVM.','Cucumber-JVM','https://github.com/cucumber/cucumber-jvm/issues','https://github.com/cucumber/cucumber-jvm','https://cucumber.io',2,'cucumber-java8','info.cukes'),
	('Y', 42,'Maven plugin which includes build-time git repository information into an POJO / *.properties). Make your apps tell you which version exactly they were built from!','maven-git-commit-id-plugin','https://github.com/ktoso/maven-git-commit-id-plugin/issues','https://github.com/ktoso/maven-git-commit-id-plugin','',52,NULL,NULL),
	('Y', 52,'jade4j''s intention is to be able to process jade templates in Java without the need of a JavaScript environment, while being fully compatible with the original jade syntax.','jade4j','https://github.com/neuland/jade4j/issues','https://github.com/neuland/jade4j','',12,NULL,NULL),
	('Y', 62,'A Spring Integration for jade4j','spring-jade4j','https://github.com/neuland/spring-jade4j/issues','https://github.com/neuland/spring-jade4j','',12,NULL,NULL),
	('Y', 72,'Maven Plugin to Compile SASS files into CSS','sass-maven-plugin','https://github.com/GeoDienstenCentrum/sass-maven-plugin/issues','https://github.com/GeoDienstenCentrum/sass-maven-plugin','',42,NULL,NULL),
	('Y', 82,'The Guava project contains several of Google''s core libraries that we rely on in our Java-based projects: collections, caching, primitives support, concurrency libraries, common annotations, string processing, I/O, and so forth.','guava','https://github.com/google/guava/issues','https://github.com/google/guava','',72,'',''),
	('Y', 92,'PowerMock is a Java framework that allows you to unit test code normally regarded as untestable.','powermock','https://github.com/jayway/powermock/issues','https://github.com/jayway/powermock','',2,NULL,NULL),
	('Y', 102,'A Java DSL for reading JSON documents.','JsonPath','https://github.com/jayway/JsonPath/issues','https://github.com/jayway/JsonPath','',62,'',''),
	('Y', 112,'Joda-Time is the widely used replacement for the Java date and time classes.','Joda-Time','https://github.com/JodaOrg/joda-time/issues','https://github.com/JodaOrg/joda-time','http://www.joda.org/joda-time/',22,NULL,NULL),
	('Y', 122,'Mocking framework for unit tests written in Java','Mockito','https://github.com/mockito/mockito/issues','https://github.com/mockito/mockito','http://mockito.org/',2,NULL,NULL),
	('Y', 132,'FluentLenium is a framework that helps you to write Selenium tests. FluentLenium provides you a fluent interface to the Selenium Web Driver. FluentLenium lets you use the assertion framework you like, either jUnit assertions, Hamcrest or AssertJ','FluentLenium','https://github.com/FluentLenium/FluentLenium/issues','https://github.com/FluentLenium/FluentLenium','',2,'fluentlenium-core','org.fluentlenium'),
	('Y', 142,'Maven plugin to execute Jasmine Specs. Creates your HTML runners for you, runs headlessly, outputs JUnit XML','jasmine-maven-plugin','https://github.com/searls/jasmine-maven-plugin/issues','https://github.com/searls/jasmine-maven-plugin','http://searls.github.io/jasmine-maven-plugin/',2,'jasmine-maven-plugin','com.github.searls'),
	('Y', 152,'Guice (pronounced ''juice'') is a lightweight dependency injection framework for Java 6 and above, brought to you by Google.','Guice','https://github.com/google/guice/issues','https://github.com/google/guice','',82,'guice','com.google.inject'),
	('Y', 162,'Core support for dependency injection, transaction management, web applications, data access, messaging, testing and more.','Spring Framework','https://jira.spring.io/browse/SPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel','https://github.com/spring-projects/spring-framework','http://projects.spring.io/spring-framework/',82,'spring-context','org.springframework'),
	('Y', 172,'Spring Cloud Config provides server and client-side support for externalized configuration in a distributed system. With the Config Server you have a central place to manage external properties for applications across all environments.','Spring Cloud Config','https://github.com/spring-cloud/spring-cloud-config/issues','https://github.com/spring-cloud/spring-cloud-config','http://cloud.spring.io/spring-cloud-config/',92,'',''),
	('Y', 182,'Lang provides a host of helper utilities for the java.lang API, notably String manipulation methods, basic numerical methods, object reflection, concurrency, creation and serialization and System properties.','Apache Commons Lang','https://issues.apache.org/jira/browse/LANG/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel','https://git-wip-us.apache.org/repos/asf?p=commons-lang.git','https://commons.apache.org/proper/commons-lang/',72,'commons-lang3','org.apache.commons'),
	('Y', 192,'AssertJ is a library of assertions similar to fest-assert but providing a richer set of assertions.','AssertJ','https://github.com/joel-costigliola/assertj-core/issues?milestone=&q=is%3Aopen','https://github.com/joel-costigliola/assertj-core','http://joel-costigliola.github.io/assertj/',2,'assertj-core','org.assertj'),
	('Y', 202,'AsciidoctorJ is the official library for running Asciidoctor on the JVM. Using AsciidoctorJ, you can convert AsciiDoc content or analyze the structure of a parsed AsciiDoc document from Java and other JVM languages.','AsciidoctorJ','https://github.com/asciidoctor/asciidoctorj/issues','https://github.com/asciidoctor/asciidoctorj','http://asciidoctor.org/',12,'asciidoctorj','org.asciidoctor'),
	('Y', 212,'Hamcrest matchers for composition','Hamcrest Compose','https://github.com/markhobson/hamcrest-compose/issues','https://github.com/markhobson/hamcrest-compose','',2,'hamcrest-compose','org.hobsoft.hamcrest'),
	('Y', 222,'Matchers that can be combined to create flexible expressions of intent','Hamcrest','https://github.com/hamcrest/JavaHamcrest/issues','https://github.com/hamcrest/JavaHamcrest','http://hamcrest.org/JavaHamcrest/',2,'hamcrest-all','org.hamcrest'),
	('Y', 232,'The plugin provides 2 goals to help execute system and Java programs.','exec-maven-plugin','https://github.com/mojohaus/exec-maven-plugin/issues','https://github.com/mojohaus/exec-maven-plugin','http://www.mojohaus.org/exec-maven-plugin/',52,'exec-maven-plugin','org.codehaus.mojo'),
	('Y', 242,'Model Citizen is an annotation based model factory for Java, inspired by FactoryGirl','Model Citizen','https://github.com/mguymon/model-citizen/issues','https://github.com/mguymon/model-citizen','',2,'core','com.tobedevoured.modelcitizen');
